### ISSUE TITLE
Add ouroboros to the user's path automagically

### ISSUE THREAD

**Issue by tlkamp** [circa10a/ouroboros#28]
Wanted to get this into an issue for discussion.

I'm planning to use `setuptools` in combination with `setup.py` to install ouroboros into the user's path at `pip install ...` time.

This will likely be a big refactor of `cli.py` and `main.py`, so to keep us all sane I'll probably split it into separate PRs.

**Comment by dannysauer** [comment]
I do like systemd's logging. ;)

**Comment by tlkamp** [comment]
I've made some good changes, but I'm having problems with the integration tests.
Why is [this test](https://github.com/circa10a/ouroboros/blob/master/tests/integration/main_test.py#L46) expected to fail?

```python
def test_main(mocker):
    mocker.patch('sys.argv', [''])
    mocker.patch.dict('os.environ',
                      {'INTERVAL': '6',
                       'LOGLEVEL': 'debug',
                       'RUNONCE': 'true',
                       'CLEANUP': 'true',
                       'MONITOR': test_container_name})
    with pytest.raises(SystemExit):
        assert imp.load_source('__main__', 'ouroboros/main.py') == SystemExit
```

**Comment by circa10a** [comment]
@tlkamp The reason for the `SystemExit`, is because the `RUNONCE` env variable is being supplied. This tells ourboros to make only one pass of updates and then exit. The reason for this is because if `RUNONCE` wasn't supplied, `main` would loop and the test would simply run until timeout.

**Comment by tlkamp** [comment]
Thinking about this, what if we made the `--runonce` and `--interval` mutually exclusive? I can't think of a good reason to supply both.

**Comment by circa10a** [comment]
Good idea! It never really crossed my mind. Bah, I feel dumber every time I talk to you.

**Comment by tlkamp** [comment]
You _learn_ every time you talk to me. You're not dumb. We just have experience in different areas :wink:

**Comment by tlkamp** [comment]
@circa10a Might need some collaboration at the end of this. Your `run_tests.sh` script is unlikely to work when this is done and I'm no bash wizard.

**Comment by dannysauer** [comment]
I might know a shell guy if you two don't get it figured out. ;)

**Comment by circa10a** [comment]
@dannysauer @tlkamp 
Deploy via `pip` seems to be working fine. I did have to use `ouroboros-cli` as the pkg name since `ouroboros` was already taken.

Here's the docs: https://github.com/circa10a/ouroboros/blob/master/README.md#pip
