### ISSUE TITLE
Add autopep8 to the pre-merge checks

### ISSUE THREAD

**Issue by tlkamp** [circa10a/ouroboros#30]
The project currently doesn't follow PEP8 formatting standards and my editor is screaming at me. Can we integrate autopep8 at some higher level to ensure all of the code is formatted properly?

**Comment by circa10a** [comment]
@tlkamp you thinking `pylint`?

I started down that route, but it keep giving me hell about the imports and couldn't get why, regardless, I'm all for it

**Comment by circa10a** [comment]
Nvm my previous comment, I just read `pep8`. Want to just add `autopep8` as part of the Travis build?

**Comment by dannysauer** [comment]
How does autopep8 differ from flake8? I ask because I was just looking at setting up flake8 in the Travis build for another project.

**Comment by circa10a** [comment]
Ran `flake8` , need to cleanup alot of files before having this as a requirement in CI. PR #31 should knock this down considerably.

@tlkamp vscode has some nice integration with `flake8` similar to `eslint`

**Comment by dannysauer** [comment]
My plan was to add an exclude option to the flake8 config on the project I was working on today, and remove files as they got cleaned up - preventing new messes from being made in the interim. :)

http://flake8.pycqa.org/en/3.1.1/user/ignoring-errors.html
http://flake8.pycqa.org/en/3.1.1/user/configuration.html#project-configuration
