### ISSUE TITLE
Add ability to ignore select containers

### ISSUE THREAD

**Issue by XScorpion2** [circa10a/ouroboros#35]
We have the ability to monitor only select containers, but if you have lots of containers and only want one or two to not be updated, it's prohibitive to add all containers to this list except for the ones you don't want updated. It also makes you update the parameters each time I add or remove a container. A simple --ignore option would be extremely helpful.

**Comment by tlkamp** [comment]
I'm in favor, and I think this would be a pretty easy addition. @circa10a?

**Comment by circa10a** [comment]
Yeah, I think it would be a nice feature to have.
Anybody want dibs?

**Comment by tlkamp** [comment]
I can take this on next.

**Comment by tlkamp** [comment]
Beginning work on this now, should be a PR in a day or two.
