### ISSUE TITLE
Kuberenetes Support

### ISSUE THREAD

**Issue by TheRealChrisThomas** [circa10a/ouroboros#49]
I got K8s on the brain and I talked to @circa10a about this last night so wanted to put this out there.

Wondering if a feature to monitor the registry and update the running pod with the new image would be beneficial?

**Comment by circa10a** [comment]
@theRealChrisThomas maybe Cooper and Eddie had some input?

Will need to dig into https://github.com/kubernetes-client/python some more

**Comment by circa10a** [comment]
Sounds like an opportunity to wreak havoc upon the codebase

**Comment by TheRealChrisThomas** [comment]
I only commit to master! Jk I'll fork when I get home.

**Comment by tlkamp** [comment]
Forks lead to borks.

**Comment by dannysauer** [comment]
Relevant:
https://kubernetes.io/docs/tutorials/kubernetes-basics/update/update-intro/

**Comment by circa10a** [comment]
Found sample code that supplements `kubtectl set new image ...`
https://github.com/kubernetes-client/python/issues/347

**Comment by TheRealChrisThomas** [comment]
Nice. I was actually just looking at this right now

**Comment by circa10a** [comment]
We'll be moving to an org soon and I feel this would serve better as it's own project under the org.

**Comment by thiagoloureiro** [comment]
Hi guys, any updates on this? It's implemented?I'm moving from docker droplets to Kubernetes and looking forward to the same solution to help me out with Kube :) Tkz!

**Comment by circa10a** [comment]
I don't think this has been looked at any recently. One option and perhaps better is [flux](https://github.com/fluxcd/flux)
