### ISSUE TITLE
Problem accessing private registry

### ISSUE THREAD

**Issue by JanLoebel** [circa10a/ouroboros#55]
Hi there,

thank you for your great project. I've a problem regarding the access of my private registry. It works if I pass the user and password directly via: `-e REPO_USER=myUser -e REPO_PASS=myPassword`

If I map the configuration via: `-v /root/.docker/config.json:/root/.docker/config.json` there is the following output (exact servername was replaced with server.com):

```
[DEBUG] 2018-11-28 09:52:46 http://localhost:None "GET /v1.35/images/portainer/portainer/json HTTP/1.1" 200 1761
[DEBUG] 2018-11-28 09:52:46 Pulling image: portainer/portainer:latest
[DEBUG] 2018-11-28 09:52:46 Sending supplied auth config
[DEBUG] 2018-11-28 09:52:47 http://localhost:None "POST /v1.35/images/create?tag=latest&fromImage=portainer%2Fportainer HTTP/1.1" 200 None
[DEBUG] 2018-11-28 09:52:47 http://localhost:None "GET /v1.35/images/portainer/portainer:latest/json HTTP/1.1" 200 1761
[DEBUG] 2018-11-28 09:52:47 http://localhost:None "GET /v1.35/images/registry.server.com/server-portfolio:latest/json HTTP/1.1" 200 None
[DEBUG] 2018-11-28 09:52:47 Pulling image: registry.server.com/server-portfolio:latest
[DEBUG] 2018-11-28 09:52:47 Sending supplied auth config
[DEBUG] 2018-11-28 09:52:48 http://localhost:None "POST /v1.35/images/create?tag=latest&fromImage=registry.server.com%2Fserver-portfolio HTTP/1.1" 500 116
[ERROR] 2018-11-28 09:52:48 500 Server Error: Internal Server Error ("Get https://registry.server.com/v2/server-portfolio/manifests/latest: no basic auth credentials")
[INFO] 2018-11-28 09:52:48 0 container(s) updated
```

The `config.json` looks like this:
```
{
        "auths": {
                "registry.codeoftheday.net": {
                        "auth": "dXNlcjpwYXNzd29yZA=="
                }
        },
        "HttpHeaders": {
                "User-Agent": "Docker-Client/18.06.1-ce (linux)"
        }
}
```

Any idea what I could try?

**Comment by circa10a** [comment]
@JanLoebel  Thanks for reporting the issue.
Docker-py should default to that location: https://docker-py.readthedocs.io/en/stable/api.html?highlight=config.json

Following the docs, can you try `-v /root/.docker/config.json:root/.dockercfg` ?

**Comment by circa10a** [comment]
Actually, this is bug since i'm using the `auth_config` parameter which overrides `login` params. So mapping in the config won't work right now. I have an idea to fix this.

**Comment by circa10a** [comment]
@JanLoebel Can you try again with v0.3.2 ?

**Comment by JanLoebel** [comment]
Tried it with both: `-v /root/.docker/config.json:/root/.dockercfg` and `-v /root/.docker/config.json:/root/.docker/config.json` and it worked :) Perfect! Thank you!!
