### ISSUE TITLE
Slack notification 

### ISSUE THREAD

**Issue by zoispag** [circa10a/ouroboros#61]
Hi, are slack notifications supported?

I cannot find anything related to notifications in the README.

**Comment by dannysauer** [comment]
A generic notification hook _would_ probably be useful.

**Comment by tlkamp** [comment]
@dannysauer agreed; limited to _outgoing_ only though. I don't think we want to turn ouroboros into a rest service 😉 

@circa10a?

**Comment by circa10a** [comment]
I can see how a generic webook would be pretty useful. I'm all for that, but I would like to keep it vanilla and not rely on any product SDK's other than docker-py.

**Comment by circa10a** [comment]
And yes @tlkamp. Outgoing only

**Comment by zoispag** [comment]
Although I would have no problem using a web hook to have Slack notifications, I kind of think Slack as an industrial standard, so I wouldn’t include it in ‘any product’-category. But that’s just my personal opinion! :)

**Comment by dannysauer** [comment]
Seems like an api with a stand-alone publisher (and it's own config file - 
or segment of a config file) would be the way to go. Maybe an environment 
variable naming convention which is passed along to the helper? Everyone 
loves insecure environment variables!

**Comment by circa10a** [comment]
Or do we just rely on basic auth using the URL and set our own headers? 🤔
Simplicity is ideal

**Comment by circa10a** [comment]
Any takers?

**Comment by circa10a** [comment]
@dannysauer environment variables are my favorite 😜

**Comment by circa10a** [comment]
@zoispag I'll take care of this tomorrow evening

**Comment by circa10a** [comment]
Update: this is working fine on it's own branch, I just need to add tests. Will work on it as I have time which may be limited due to the holidays

**Comment by circa10a** [comment]
@zoispag, let me know if you have any issues using the new webook functionality
