### ISSUE TITLE
Add Schedule Functionality

### ISSUE THREAD

**Issue by PhasecoreX** [circa10a/ouroboros#63]
Back in the Watchtower days, we had the "--schedule" feature. Instead of specifying an interval to perform checks, you could define a cron-like schedule to perform updates. That way, you could have your containers update at 5am every day, when you or others aren't using your containers. Or, you could have it update every hour on the hour, instead of being relative to when the Ouroboros container started.

I would love to see this feature implemented! As an aside, the ability to specify a time zone would probably be nice to have as well, for ease of scheduling.

**Comment by circa10a** [comment]
I'm a little on the fence on adding this to app for a couple of reasons:

There's nothing stopping a user from implementing their own crontab that does:

via docker
```
*  5  *  *  * docker run --rm -d --name ouroboros -v /var/run/docker.sock:/var/run/docker.sock circa10a/ouroboros --interval 1 --runonce
```
via pip installed cli

```bash
*  5  *  *  * ouroboros --interval 1 --runonce
```

This allows ouroboros to run one time then boom, done. With the user handling their own schedule details.

The other reason is because I couldn't find a good python lib to handle the crontab syntax for executing functions. I'd have to build my own regex parser which isn't a huge deal, but feels kind of hacky. I'm totally against the idea, I guess I'm just trying to weigh the advantages of having it vs using regular cron.

Thoughts @dannysauer @tlkamp ?

**Comment by tlkamp** [comment]
@circa10a I have to agree. I don't want to go reinventing a scheduling tool that's still very widely used

**Comment by circa10a** [comment]
Maybe just add some sweet docs for scheduling?

**Comment by dannysauer** [comment]
Strongly seconded. Using cron (or, even better, systemd timers - which would allow for "service 2 update happens when service 1 is back up" and "only run update if service 3 is running and service 4 is not" kinds of complex logic) is the right way to do this.

**Comment by dannysauer** [comment]
Arch Linux provides some nice documentation on use of timers at https://wiki.archlinux.org/index.php/Systemd/Timers.

**Comment by circa10a** [comment]
Sounds like it's decided. We won't add it to the application, but will be sure to provide docs around the subject.

**Comment by PhasecoreX** [comment]
I went ahead and created a Docker image that extends this one and includes cron in it: https://hub.docker.com/r/phasecorex/ouroboros-scheduler. It serves my needs, and completely replaces how I was using Watchtower. Maybe others who used the `--schedule` argument in Watchtower will find use in this as well.

I like relying on the underlying OS as little as possible. That way, my Docker containers won't break if I move them to a host missing certain programs (cron) or using a different init system. The more the container can do on it's own, the better.

**Comment by circa10a** [comment]
@PhasecoreX Very cool! That's what open source is all about. Be sure to set up an automated build so you can continually get the new features!

**Comment by circa10a** [comment]
@PhasecoreX
One thing I want to add, in your repo you said that the args aren't changeable. All of ouroboros' args can be interchanged with environment variables, so you can indeed modify the parameters without hardcoding them in the entrypoint. You can see the environment variables in the README
