### ISSUE TITLE
Add output to log at container start

### ISSUE THREAD

**Issue by haribert** [circa10a/ouroboros#66]
It would be great to have an output in the Docker container at the beginning. For example with all given arguments:
```
Ouroboros container started with following configuration: interval: 43200, cleanup: true, keeptag: true, loglevel: info, ... next run time: ....
```

Otherwise you do not have any output until the first run (which can be dependent on the interval 12 hours later) and you are not sure if the container is running (with the correct configuration).

**Comment by tlkamp** [comment]
We can accommodate this.

**Comment by circa10a** [comment]
Will have to leave the "container" word out since it can also be started with the raw cli
