### ISSUE TITLE
Timezone Support

### ISSUE THREAD

**Issue by andrewjmetzger** [circa10a/ouroboros#68]
As of Ouroboros v0.3.6. all times are in UTC when running inside a Docker container.

Consider adding support for timezones to Ouroboros; this could make scheduling and logging simpler. 

----

Some Docker images (such as those from LinuxServer.io) support the use of an optional timezone offset, specified as an environment variable.  For example, to use Eastern Standard Time (UTC -5):

```
sudo docker run \
  --name ouroboros \
  -e INTERVAL=300 \
  -e LOGLEVEL=debug \
  -e CLEANUP=true \
  -e KEEPTAG=true \
  -e TZ=America/New_York \
  -v /var/run/docker.sock:/var/run/docker.sock \
circa10a/ouroboros
```

This would potentially require also mounting `/etc/timezone` from the host, although further investigation is needed.

**Comment by circa10a** [comment]
Adding the TZ environment variable should be the only thing you need to do for this to work. Have you tried it?

` -e TZ=America/Detroit`

**Comment by circa10a** [comment]
I think we need to add `tzdata` to the docker image.

`RUN apk add --no-cache tzdata`
