### ISSUE TITLE
Installation via pip fails

### ISSUE THREAD

**Issue by jmbegley** [circa10a/ouroboros#73]
Attempting to install ouroboros via pip fails:

[james@jumbopi ~]$ pip3 install ouroboros-cli
Collecting ouroboros-cli
  Downloading https://files.pythonhosted.org/packages/7c/9a/12b2ab81d496250c2c6c1f3311a596c909bd6469314f74a2774ab28c8b07/ouroboros-cli-0.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-lky8b4ho/ouroboros-cli/setup.py", line 25, in <module>
        install_requires=read_reqs(requirements='./requirements.txt'),
      File "/tmp/pip-install-lky8b4ho/ouroboros-cli/setup.py", line 10, in read_reqs
        with open(requirements) as f:
    FileNotFoundError: [Errno 2] No such file or directory: './requirements.txt'

There is no file "requirements.txt" included in the tar file downloaded from pythonhosted.org (I think its called "requires.txt" instead).

Note that I only tried the pip installation method since the docker image also fails on the Raspberry Pi 3B+ (which uses a different ARM chip, so it would need an ARM8 64 / aarch64 docker image).

**Comment by circa10a** [comment]
@jmbegley Thanks for reporting the issue!
I've fixed the pip install in `0.4.2` and will work on getting an ARM8 docker image together later today.

**Comment by dannysauer** [comment]
Seems to behave as expected on my Pi 3b+ running SUSE; and (as expected) doesn't run on my Pi 3b with Raspbian. :D

**Comment by circa10a** [comment]
Thanks for the confirmation @dannysauer !
