### ISSUE TITLE
grafana to metrics/prometheus endpoint

### ISSUE THREAD

**Issue by DirtyCajunRice** [circa10a/ouroboros#74]
![example](https://bin.cajun.pro/images/firefox_LqFVlFQ0Su.png)
I dont seem to be able to connect via grafana with Prometheus datasource. curling http://ouroboros:8000/ within my container yields the expected results. Has anyone set this up and how?

**Comment by circa10a** [comment]
grafana won't be able to talk directly to Ouroboros. The data first needs to be ingested by a Prometheus instance, then you would point grafana at Prometheus.

https://prometheus.io/docs/introduction/first_steps/

Let me know if you still aren't able to get the integration to work, I can help walk you through it.
